#!/bin/bash
# Genere par yunopack. Symetrique du script d'installation.

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# REPERTOIRES
#=================================================
ynh_script_progression "Restauration des fichiers de $app..."

ynh_restore "$install_dir"
chown -R "$app:www-data" "$install_dir"

ynh_restore "$data_dir"

#=================================================
# CONFIGURATIONS SYSTEME
#=================================================
ynh_script_progression "Restauration des configurations systeme..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="Yunopack" --log="/var/log/$app/$app.log"
ynh_restore "/etc/logrotate.d/$app"
mkdir -p "/var/log/$app"
chown -R "$app:www-data" "/var/log/$app"
ynh_restore "/var/log/$app/"

#=================================================
# RECHARGEMENT DES SERVICES
#=================================================
ynh_script_progression "Rechargement de NGINX et du service de $app..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service=nginx --action=reload

#=================================================
# FIN DU SCRIPT
#=================================================

ynh_script_progression "Restauration de $app terminee"
